accomodation:
    id: 100
    children:
        tourism:
            alpine_hut: 101
            apartment: 102
            camp_site: 103
            caravan_site: 104
            chalet: 105
            guest_house: 106
            hostel: 107
            hotel: 108
            motel: 109
            wilderness_hut: 110

animals:
    id: 120
    children:
        amenity:
            animal_boarding: 121
            animal_shelter: 122
            veterinary: 123
        shop:
            pet: 124

arts_and_culture:
    id: 130
    children:
        amenity:
            arts_centre: 131
            library: 133
            place_of_worship: 135
            studio: 136
        tourism:
            gallery: 132
            museum: 134

education:
    id: 150
    children:
        amenity:
            college: 151
            driving_school: 152
            kindergarten: 153
            language_school: 154
            music_school: 155
            school: 156
            university: 157

facilities:
    id: 160
    children:
        amenity:
            compressed_air: 161
            bench: 162
            emergency_phone: 163
            clock: 164
            drinking_water: 166
            hunting_stand: 168
            internet_cafe: 169
            kneipp_water_cure: 170
            post_box: 171
            recycling: 172
            sanitary_dump_station: 174
            shelter: 175
            shower: 176
            table: 177
            telephone: 178
            toilets: 179
            waste_basket: 180
            waste_disposal: 181
            water_point: 182
        emergency:
            access_point: 205
            defibrillator: 165
            fire_hydrant: 167

financial:
    id: 190
    children:
        amenity:
            atm: 191
            bank: 192
            bureau_de_change: 193

healthcare:
    id: 200
    children:
        amenity:
            baby_hatch: 201
            clinic: 202
            dentist: 203
            doctors: 204
            hospital: 206
            nursing_home: 207
            pharmacy: 208
            retirement_home: 209
            social_facility: 210
        healthcare:
            blood_donation: 211

historic:
    id: 220
    children:
        historic:
            aircraft: 221
            aqueduct: 222
            archaeological_site: 223
            castle: 224
            cannon: 225
            city_gate: 226
            citywalls: 227
            battlefield: 228
            boundary_stone: 229
            building: 230
            farm: 231
            fort: 232
            gallows: 233
            highwater_mark: 234
            locomotive: 235
            manor: 236
            memorial: 237
            milestone: 238
            monastery: 239
            monument: 240
            optical_telegraph: 241
            pillory: 242
            ruins: 243
            rune_stone: 244
            ship: 245
            tomb: 246
            wayside_cross: 247
            wayside_shrine: 248
            wreck: 249

leisure_and_entertainment:
    id: 260
    children:
        leisure:
            adult_gaming_centre: 261
            amusement_arcade: 262
            beach_resort: 263
            bandstand: 264
            bird_hide: 265
            common: 266
            dance: 267
            dog_park: 268
            firepit: 269
            fishing: 270
            fitness_centre: 271
            garden: 272
            golf_course: 273
            hackerspace: 274
            horse_riding: 275
            ice_rink: 276
            marina: 277
            miniature_golf: 278
            nature_reserve: 279
            park: 280
            picnic_table: 281
            pitch: 282
            playground: 283
            sauna: 286
            slipway: 287
            sports_centre: 288
            stadium: 289
            summer_camp: 290
            swimming_area: 291
            swimming_pool: 292
            track: 293
            turkish_bath: 294
            water_park: 295
            wildlife_hide: 296
        highway:
             raceway: 284
        amenity:
            brothel: 297
            casino: 298
            cinema: 299
            dive_centre: 300
            dojo: 301
            gambling: 302
            nightclub: 303
            planetarium: 304
            public_bath: 285
            social_centre: 305
            spa: 306
            stripclub: 307
        tourism:
            aquarium: 308
            theme_park: 309
            zoo: 310

natural:
    id: 330
    children:
        natural:
            cave_entrance: 331
            beach: 332
            geyser: 333
            peak: 335
            rock: 336
            saddle: 337
            spring: 338
            volcano: 339
            water: 340

public_places:
    id: 360
    children:
        amenity:
            embassy: 361
            crematorium: 362
            community_centre: 363
            courthouse: 364
            coworking_space: 365
            crypt: 366
            fire_station: 367
            grave_yard: 368
            police: 369
            post_office: 370
            prison: 371
            ranger_station: 372
            rescue_station: 373
            townhall: 374

service:
    id: 390
    children:
        shop:
            beauty: 391
            estate_agent: 392
            dry_cleaning: 393
            glaziery: 394
            hairdresser: 395
            laundry: 396
            massage: 397
            tailor: 399
            tattoo: 400
        amenity:
            photo_booth: 398

shops:
    id: 420
    children:
        shop:
            agrarian: 421
            alcohol: 422
            antiques: 423
            art: 424
            bag: 425
            bakery: 426
            bed: 427
            beverages: 428
            bicycle: 429
            books: 430
            boutique: 431
            brewing_supplies: 432
            business_machines: 433
            butcher: 434
            cafe: 435
            camera: 436
            candles: 437
            car: 438
            car_parts: 439
            carpet: 440
            curtain: 441
            cheese: 442
            chemist: 443
            chocolate: 444
            clothes: 447
            coffee: 448
            computer: 449
            confectionery: 450
            convenience: 451
            copyshop: 452
            cosmetics: 453
            dairy: 454
            deli: 455
            department_store: 456
            doityourself: 457
            electrical: 458
            electronics: 459
            erotic: 460
            e-cigarette: 461
            farm: 462
            fashion: 463
            fishing: 464
            florist: 465
            funeral_directors: 466
            furniture: 467
            games: 468
            garden_centre: 469
            garden_furniture: 470
            gas: 471
            general: 472
            gift: 473
            greengrocer: 474
            grocery: 475
            interior_decoration: 476
            hairdresser_supply: 477
            hardware: 478
            hearing_aids: 479
            herbalist: 480
            hifi: 481
            houseware: 482
            hunting: 483
            insurance: 484
            jewelry: 485
            leather: 486
            locksmith: 487
            kiosk: 488
            kitchen: 489
            lamps: 490
            lottery: 491
            mall: 492
            medical_supply: 494
            mobile_phone: 495
            model: 496
            motorcycle: 497
            music: 498
            musical_instrument: 499
            nutrition_supplements: 500
            newsagent: 501
            optician: 502
            organic: 503
            outdoor: 504
            paint: 505
            pastry: 506
            perfumery: 507
            photo: 508
            pyrotechnics: 509
            radiotechnics: 510
            seafood: 511
            second_hand: 512
            security: 513
            shoes: 514
            spices: 515
            sports: 516
            stationery: 517
            supermarket: 518
            swimming_pool: 519
            tea: 520
            ticket: 521
            tiles: 522
            tobacco: 523
            toys: 524
            trophy: 525
            tyres: 526
            variety_store: 527
            video: 529
            video_games: 530
            watches: 531
            weapons: 532
            wine: 533
        amenity:
            marketplace: 493
            vending_machine: 528

sustenance:
    id: 560
    children:
        amenity:
            bar: 561
            bbq: 562
            biergarten: 563
            cafe: 564
            drinking_water: 565
            fast_food: 566
            food_court: 567
            ice_cream: 568
            pub: 569
            restaurant: 570

transport:
    id: 580
    children:
        aeroway:
            aerodrome: 581
            helipad: 598
            heliport: 599
        amenity:
            bicycle_parking: 583
            bicycle_rental: 584
            bicycle_repair_station: 585
            boat_sharing: 586
            bus_station: 587
            bus_stop: 588
            car_rental: 589
            car_repair: 590
            car_sharing: 591
            car_wash: 592
            charging_station: 593
            ev_charging: 594
            ferry_terminal: 595
            fuel: 596
            motorcycle_parking: 600
            parking: 601
            parking_entrance: 602
            parking_space: 603
            taxi: 606
        railway:
            halt: 597
            station: 604
            tram_stop: 605
        public_transport:
          platform: 607
          stop_position: 608
          stop_area: 609
          station: 610

tourism:
    id: 620
    children:
        tourism:
            artwork: 621
            attraction: 622
            information: 624
            picnic_site: 625
            viewpoint: 627
        amenity:
            fountain: 623
        shop:
            travel_agency: 626
